### ISSUE TITLE
glNext support

### ISSUE THREAD

**Issue by pizthewiz** [BanTheRewind/Cinder-Asio#11]
It looks like two things need to be done to support glNext:
1. Migrate from Boost ASIO to standalone ASIO
2. Update the samples

PR #10 updates the UDP samples, but requires an older rev like cinder/Cinder@bea6a85 before standalone ASIO was integrated.

**Comment by pizthewiz** [comment]
Initial support landed in c5870439, the only hang up I'm now seeing is that the `WaitTimer` can't find the `deadline_timer` type:
```sh
/Users/pizthewiz/sandbox/Cinder/Cinder/blocks/Cinder-Asio/src/WaitTimer.h:62:8: No type named 'deadline_timer' in namespace 'asio'
```

which is strange as asio.hpp has:
```c++
#include "asio/deadline_timer.hpp"
```

which provides the typedefs:
```c++
typedef basic_deadline_timer<boost::posix_time::ptime> deadline_timer;
```

Perhaps related to the boost date and time use?

**Comment by BanTheRewind** [comment]
Ah, I built the latest glNext without updating the boost submodule. Date and time were removed from Cinder's boost. I'll work on a solution tomorrow.

**Comment by BanTheRewind** [comment]
This is fixed in ca4a4b140754d918262fba7fe68bd608c8846577.

**Comment by pizthewiz** [comment]
Hmm, none of the samples are building for me on OS X with glNext HEAD. The precompiled header files need a quick tweak to remove some now bad includes (if helpful, I can quickly PR that), but all the projects are blowing up complaining that `asio::placeholders` doesn't have a member `error`, `iterator` or `bytes_transferred`.

**Comment by BanTheRewind** [comment]
Weird. I'm on Windows, but a colleague of mine just now built the TCP samples in Xcode. The build error you are getting is weird. I have placeholders.hpp open and am looking at error (line 33), iterator (44) and bytes_transferred (39) right now.

**Comment by pizthewiz** [comment]
Mysterious, my Cinder is at rev 4f6e50f, the boost submodule is sitting at rev c3e41de and Cinder-Asio at 228b91c. Maybe a toolchain issue, I'm on 10.10.3 and have tried Xcode 6.2 and Xcode 6.3 beta 3 with the TcpClient sample and still hit the strange placeholder issue:
![](http://i.imgur.com/EbqB7ph.png)

**Comment by pizthewiz** [comment]
AH HA! Apparently like on Windows, the `CinderAsio.h` include must occur before the Cinder library. The catch with OS X (and I suppose iOS as well) is that the Cinder library include is actually processed in most Cinder apps via the precompiled header!

**Comment by pizthewiz** [comment]
Xcode project tweaks PR'ed as #14 I think this is now good to close.
