### ISSUE TITLE
WaitTimer.h:62:8: No type named 'deadline_timer' in namespace 'asio'

### ISSUE THREAD

**Issue by xumo** [BanTheRewind/Cinder-Asio#17]
I'm using Cinder glNext. Maybe I have mixed boost version.
Any hints?

**Comment by pizthewiz** [comment]
Is your Boost submodule in sync and have you changed the `#include` order? More discussion is in #11.

**Comment by xumo** [comment]
Yeah, I changed the #include order.

I just cloned cinder glNext again with boost_1_58, but no luck so far. Still trying

**Comment by xumo** [comment]
Moved in the precompiled header. and that solved.
